Add Indonesian translation
teaxyz/white-paper pull request #67
Opened 2022-09-05 10:02 UTC by kribolista

- [x] translate metadata
- [x] translate white-paper

2022-09-06 17:32 UTC, mfts requested changes
Please see my change requests inline.

2022-09-06 17:32 UTC, mfts commented on i18n/id/white-paper.md
> +[Tampilan sederhana dari sistem imbalan seduhan tea.] (img/figure-1.svg)
Please add `!` in front of the [] to indicate it's an image and no spaces between `[]()`

2022-09-06 17:32 UTC, mfts commented on i18n/id/white-paper.md
> +Sistem bukti kepemilikan yang didukung oleh token tea akan memungkinkan pemegang token tea untuk berkontribusi pada keamanan sistem dengan *mengambil* tea dan mendukung pengembang sumber terbuka deng
> ($ 10 ^ {{-8} $)

Something odd happened here. The formula is not displayed properly. Please double-check in the `white-paper.md` for reference.

2022-09-06 17:32 UTC, mfts commented on i18n/id/white-paper.md
> +Tujuan tea adalah untuk mewakili nilai perangkat lunak sumber terbuka dan, dengan demikian, mendorong pertumbuhannya dengan memberdayakan para pesertanya dengan sumber daya yang mereka butuhkan untuk
> [^ 19]

There should be no space between the characters --> [^19]

2022-09-06 17:32 UTC, mfts commented on i18n/id/white-paper.md
> +Saat paket curam mendekati rasio curam optimal yang ditentukan oleh tata kelola, rasio imbalan curamnya akan menurun secara progresif. Ketika sebuah paket melebihi rasio seduhan optimalnya, rasio imb
> $0$$ dan $1$$

too many `$` symbols. It should be only `$0$` and `$1$`.

2022-09-06 17:32 UTC, mfts commented on i18n/id/white-paper.md
> +Tujuan tea adalah untuk mewakili nilai perangkat lunak sumber terbuka dan, dengan demikian, mendorong pertumbuhannya dengan memberdayakan para pesertanya dengan sumber daya yang mereka butuhkan untuk
Please double-check your references. According to the white-paper.md file, this should be reference `[^22]`

2022-09-06 18:35 UTC, kribolista commented
- [x] Please add ! in front of the [] to indicate it's an image and no spaces between []()
- [x] ($ 10 ^ {{-8} $)
- [x] There should be no space between the characters --> [^19]
- [x] too many $ symbols. It should be only `$0$` and `$1$`

2022-09-06 19:06 UTC, aalifax commented
hi, can I get involved in this translation project?

2022-09-07 15:15 UTC, mfts approved these changes
Thank you for implemented the changes, @kribolista.

2022-09-07 15:15 UTC, mfts commented
@Xercesblu3 this is ready to merge from my point of view

2022-09-08 10:17 UTC, mfts commented
@Xercesblu3 please wait on the merge until we figured out the situation with the other Indonesian translations. I'm currently in contact with all 4 translators.

2022-09-20 13:14 UTC, closed without merging