Update and rename white-paper.md to white-paper-ko.md
teaxyz/white-paper pull request #69
Opened 2022-09-06 05:09 UTC by big1219

Korean Translation

- [x] translate metadata
- [ ] translate white-paper

2022-09-06 17:01 UTC, mfts commented
Hi @big1219, first of all, thank you for your submission.  

I noticed that you are replacing the original `white-paper.md` with your translated version. Please **don't delete** the original `white-paper.md` file, instead please create a folder in the root repository called `i18n` and within that another folder with your language ISO code `ko` (see below):
```
...
i18n/
  ko/
...
```
Then please place both the translated files `white-paper.md` and `metadata.yml` in the newly created folder.

2022-10-07 13:09 UTC, mfts commented
@big1219 your translation looks great. The only part missing is the translation of the `metadata.yml` file. Please let me know if you need any help with that.

2022-12-21 10:25 UTC, mfts commented
Hi @big1219 thank you for your translations work. The only file missing a Korean translation is the `metadata.yml` https://github.com/teaxyz/white-paper/pull/69/files#diff-8119a25eed95c54cb705261a7a81af1e871179ebe5cdc24bd753c6c7ecf0e104 

Let me know if there's anything I can help you with.

2022-12-22 00:41 UTC, big1219 commented
Hi ser

I need your help. What shall i do?
I do not know what wrong?
Thank you
-----Original Message-----
From: "Marc ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>; ***@***.***>;
Sent: 2022-12-21 (수) 19:25:46 (GMT+09:00)
Subject: Re: [teaxyz/white-paper] Korean Translation (PR #69)

Hi @big1219 thank you for your translations work. The only file missing a Korean translation is the metadata.yml https://github.com/teaxyz/white-paper/pull/69/files#diff-8119a25eed95c54cb705261a7a81af1e871179ebe5cdc24bd753c6c7ecf0e104
Let me know if there's anything I can help you with.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-12-22 02:14 UTC, jhheider commented
I believe the `abstract:` key in your `metadata.yml` need to be translated: https://github.com/teaxyz/white-paper/pull/69/files

2022-12-23 10:14 UTC, mfts requested changes
Changes requested in the `metadata.yml` file

2022-12-23 10:14 UTC, mfts commented on i18n/ko/metadata.yml
> +  by enacting proportional slashing events.
@big1219 please translate these sentences to English :)

2024-05-01 14:46 UTC, Edoseptian17 approved these changes

2024-05-01 19:10 UTC, closed without merging