add indonesia translation
teaxyz/white-paper pull request #75
Opened 2022-09-08 06:07 UTC by civiel024

2022-09-19 18:12 UTC, mfts requested changes
There's currently an issue with compiling this to PDF. I will have to debug it.

2022-09-19 18:12 UTC, mfts commented on i18n/id/metadata.yml
> +header-includes:
please remove this. It's redundant and causes an error

2022-09-19 18:12 UTC, mfts commented on i18n/id/metadata.yml
> +  - \fancyfoot[L]{v1.0.3+id}   # expand these variables!
please indent this line properly

```suggestion
- \fancyfoot[L]{v1.0.3+id}   # expand these variables!
```

2022-09-19 18:13 UTC, mfts commented on i18n/id/metadata.yml
> +header-includes:
**only line 81**

2022-09-20 17:19 UTC, mfts requested changes
The current build is breaking because you have translated some of the formula in the file. I mentioned inline the formula I noticed, but please check the entire document again.

2022-09-20 17:19 UTC, mfts commented on i18n/id/white-paper.md
> +\bemula{selaraskan*}
```suggestion
\begin{align*}
```

2022-09-20 17:19 UTC, mfts commented on i18n/id/white-paper.md
> +\end{selaras*}
```suggestion
\end{align*}
```

2022-09-20 17:19 UTC, mfts commented on i18n/id/white-paper.md
> +\end{selaras*}
Please check the formulas again. You have translated some of the subscript like _all_ and _ideal_ inside the formula that shouldn't be translated. 

I didn't check everywhere in the white-paper. But please make sure you don't translate formulas. 

Please refer to the locations in the original file here: https://github.com/teaxyz/white-paper/blob/main/white-paper.md?plain=1#L471 to make sure you are not overwriting any formula.

2022-09-21 16:26 UTC, mfts requested changes
Looks great, there's a minor issue in with the `-` character, so I suggested a change to a difference dash. 

Other than that it's ready to merge.

2022-09-21 16:26 UTC, mfts commented on i18n/id/metadata.yml
> +title: Protokol Terdesentralisasi untuk Remunerasi Open‑Source Ecosystem
```suggestion
title: Protokol Terdesentralisasi untuk Remunerasi Open Source Ecosystem
```

2022-09-21 16:38 UTC, civiel024 commented on i18n/id/metadata.yml
> +title: Protokol Terdesentralisasi untuk Remunerasi Open‑Source Ecosystem
done sir

2022-09-21 16:42 UTC, mfts commented on i18n/id/metadata.yml
> +title: Protokol Terdesentralisasi untuk Remunerasi Open‑Source Ecosystem
Thank you

2022-09-21 16:44 UTC, mfts approved these changes
@Xercesblu3 please run the workflow and if it compiles successfully please merge :)

2022-09-21 19:25 UTC, mfts commented
@Xercesblu3 all checks pass. Please merge 🚀

2022-09-21 19:57 UTC, merged