Update and rename white-paper.md to white-paper-zh.md
teaxyz/white-paper pull request #78
Opened 2022-09-15 13:59 UTC by lovecity08

Chinese version of White Paper

2022-09-15 14:51 UTC, mfts commented
Hi @lovecity08 

I noticed that you are replacing the original `white-paper.md` with your translated version. Please **don't delete** the original `white-paper.md` file, instead please create a folder in the root repository called `i18n` and within that another folder with your language ISO code `zh` (see below):
```
...
i18n/
  zh
...
```
Then please place both the translated files `white-paper.md` and `metadata.yml` in the newly created folder.

2022-09-15 14:52 UTC, mfts commented
Additionally, I saw that you opened two PRs; one for each file. Please add both `metadata.yml` and `white-paper.md` in the same PR. 

The second PR is here: #79

2022-09-20 17:42 UTC, mfts requested changes
Please fix the small details in the `metadata.yml` file

2022-09-21 16:16 UTC, mfts commented
@Xercesblu3 please run workflow

2022-09-22 14:40 UTC, mfts requested changes
Small fixes in the metadata.yml file

2022-09-22 14:40 UTC, mfts commented on i18n/zh/metadata.yml
> + 稳定的发布，并允许社区来管理其开源生态系统的区域，而不受外部议程的影响。
```suggestion
  为所有开源软件创建一个开放、公共和稳定的注册表将使项目能够独立发布版本，而不是
  依赖于将这些不规则数据组装到数百个独立（和重复）系统中的第三方。Package维护者将
  他们的作品发布到由拜占庭容错区块链驱动的去中心化注册表，以消除单一故障源，提供
  稳定的发布，并允许社区来管理其开源生态系统的区域，而不受外部议程的影响。
```

Please properly indent this

2022-09-22 14:40 UTC, mfts commented on i18n/zh/metadata.yml
> +- \fancyfoot[L]{${VERSION 1}+${zh}}
```suggestion
- \usepackage{fancyhdr,ragged2e}
- \lhead{\parbox[t]{0.5\textwidth}{\RaggedRight\rightmark\strut}}
- \rhead{\parbox[t]{0.5\textwidth}{\RaggedLeft\leftmark\strut}}
- \setlength{\headheight}{5\baselineskip}
- \pagestyle{fancy}
- \fancyfoot[LE,RO]{© 2022 tea.inc.}
- \fancyfoot[L]{v1.0.3+zh}
```

add missing header-includes items

2022-09-22 14:50 UTC, mfts commented
@jhheider Georgia doesn't support Chinese characters #90

2022-09-22 15:45 UTC, Xercesblu3 commented
@mfts it's not letting me run. Possibly because of the failed checks?

2022-09-22 15:47 UTC, jhheider commented
> @jhheider Georgia doesn't support Chinese characters #90 

Ugh. Hopefully we can find a single font that does what we need.

2022-09-22 16:36 UTC, mfts commented
> @mfts it's not letting me run. Possibly because of the failed checks? 

I think that's because I'm requesting changes from the PR author.

2022-10-07 12:59 UTC, mfts commented
Thank you @lovecity08 for your contribution. Everything works well. I merged your contribution into a new PR to add the font for Chinese.

Merged into #92

2022-10-07 12:59 UTC, closed without merging