add zh translation
teaxyz/white-paper pull request #80
Opened 2022-09-16 04:41 UTC by alphacute

add zh translation

2022-09-19 18:17 UTC, mfts requested changes
Some parts are missing translation

2022-09-19 18:17 UTC, mfts commented on i18n/zh/white-paper.md
> +# References
I think you missed the translations for this section here

2022-09-19 18:17 UTC, mfts commented on i18n/zh/metadata.yml
> +  by enacting proportional slashing events.
Please also translate the title and abstract

2022-09-19 18:18 UTC, mfts commented
Thank you @alphacute for the submission. We already have a Chinese translation from here: #78 and #79; perhaps you and @lovecity08 can work together on your translation.

2022-09-22 14:22 UTC, lovecity08 commented
I have been in contact with her and reviewed the Chinese translation

2022-10-07 13:03 UTC, mfts commented
Thank you @alphacute for your contribution. We can only publish one translation per language and @lovecity08 submitted his first. I have since merged it into #92 and will be public soon. You are more than welcome contribute the Chinese translation once it's published or to any another language. 

We will make sure to mention you as an honorable contributor.

2022-10-07 13:03 UTC, closed without merging