Add Bulgarian translation
teaxyz/white-paper pull request #84
Opened 2022-09-21 10:53 UTC by Keithbm1

- [x] I created a new folder `i18n/[LANG]` for my translated files
- [x] I translated `metadata.yml` file
- [ ] I translated `white-paper.md` file

2022-09-21 16:09 UTC, mfts commented on i18n/bg/metadata.yml
> + - \fancyfoot[L]{v1.0.3+bg}   # expand these variables!
```suggestion
- \fancyfoot[L]{v1.0.3+bg}   # expand these variables!
```

this needs to be properly aligned

2022-09-21 16:17 UTC, mfts commented
@Xercesblu3 please run workflow

2022-09-22 12:58 UTC, Keithbm1 commented on i18n/bg/metadata.yml
> + - \fancyfoot[L]{v1.0.3+bg}   # expand these variables!
@mfts Hello, I copied the white-paper translation from my other PR the i18n/bg folder.
So now, I can close the other PR#83?

2022-09-22 13:54 UTC, mfts commented on i18n/bg/metadata.yml
> + - \fancyfoot[L]{v1.0.3+bg}   # expand these variables!
@Keithbm1 Thank you and yes you can close #83 now

2022-09-22 14:14 UTC, mfts requested changes
Minor details that need to be fixed. Otherwise looks really good and almost ready to be merged

2022-09-22 14:14 UTC, mfts commented on i18n/bg/metadata.yml
> +Създаването на отворен, публичен и стабилен регистър за целия софтуер с отворен код
```suggestion
  Създаването на отворен, публичен и стабилен регистър за целия софтуер с отворен код 
```

Please properly indent as this is YAML and correct indents are important

2022-09-22 14:14 UTC, mfts commented on i18n/bg/metadata.yml
> +  - Svetlana Fyodorovna Dulapchi
```suggestion
- Svetlana Fyodorovna Dulapchi
```
Improved indention

2022-09-22 14:14 UTC, mfts commented on i18n/bg/white-paper.md
> +![Steeping rewards distribution across dependencies.](img/figure-2.svg){#фиг:заключване-награди}
Please change the translation of the reference key back from `фиг` back to `fig` 

And please instead translate: 

- "Dependencies analysis diagram."
- "Steeping rewards distribution across dependencies."

2022-09-23 14:30 UTC, Keithbm1 commented on i18n/bg/white-paper.md
> +![Steeping rewards distribution across dependencies.](img/figure-2.svg){#фиг:заключване-награди}
@mfts changes Updated. It will take me a little time to re-check the translation for possible spelling mistakes in Bulgarian

2022-09-27 14:48 UTC, Keithbm1 commented on i18n/bg/white-paper.md
> +![Steeping rewards distribution across dependencies.](img/figure-2.svg){#фиг:заключване-награди}
@mfts Hello, are there more changes that I have to fix up? 
I have re-checked the translation for possible spelling mistakes in Bulgarian. What are the next steps? Thank's

2022-10-04 14:41 UTC, mfts commented on i18n/bg/white-paper.md
> +![Steeping rewards distribution across dependencies.](img/figure-2.svg){#фиг:заключване-награди}
@Keithbm1 thank you for your effort. Everything works now and it's ready for publication!

2022-10-04 14:42 UTC, mfts approved these changes
Compiles locally and is ready to merge, @Xercesblu3 

We could wait for @jhheider to fix the CI but I tested it locally (which works) and it's approved to merge from my end.

2022-10-04 14:57 UTC, Xercesblu3 commented
Will wait for Jacob'a fix before merging.

2022-10-11 00:05 UTC, mfts commented
@Xercesblu3 bulgarian translation is ready for merge

2022-10-11 17:20 UTC, merged