[RU]: translation
teaxyz/white-paper pull request #91
Opened 2022-09-26 18:09 UTC by ArionThinker

- [x] I created a new folder `i18n/[LANG]` for my translated files
- [x] I translated `metadata.yml` file
- [x] I translated `white-paper.md` file
- [ ] Tag @teaxyz to enable CI (if not run by default)
- [ ] Ensure all CI checks pass
- [ ] Review CI-generated PDF artifact to ensure correct generation

2022-10-04 14:23 UTC, mfts requested changes
~~Requesting small changes~~

EDIT: changes implemented

2022-10-04 14:23 UTC, mfts commented on i18n/ru/metadata.yml
> +- \fancyfoot[LE,RO]{© 2022 tea.inc.}
```suggestion
- \fancyfoot[LE,RO]{© 2022 tea.inc.}
- \fancyfoot[L]{v1.0.3+ru}
lang: ru
dir: ltr
translator:
- Рябченко Андрій
```

Please add these so that the translation will work

2022-10-04 14:42 UTC, mfts approved these changes
Compiles locally and is ready to merge, @Xercesblu3 

We could wait for @jhheider to fix the CI but I tested it locally (which works) and it's approved to merge from my end.

2022-10-11 00:04 UTC, mfts commented
@Xercesblu3 russian translation is ready for merge

2022-10-11 17:20 UTC, Xercesblu3 commented
Merging!

2022-10-11 17:20 UTC, merged